"""
Generates a sponsor-ready PDF report using reportlab.
"""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from src.model.predict import PredictionResult

RISK_COLORS = {
    "low": colors.HexColor("#1D9E75"),
    "medium": colors.HexColor("#EF9F27"),
    "high": colors.HexColor("#E24B4A"),
}


def generate_pdf_report(
    username: str,
    profile: dict,
    features: dict,
    result: PredictionResult,
    ai_summary: str,
) -> bytes:
    """Returns PDF as bytes — pass directly to Streamlit download button."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph(f"Influencer Authenticity Report", styles["h1"]))
    story.append(Paragraph(f"@{username} · {datetime.now().strftime('%d %b %Y')}", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))

    # Score badge
    risk_color = RISK_COLORS.get(result.risk_level, colors.gray)
    score_data = [[
        f"Fake Score: {result.fake_score}/100",
        f"Risk: {result.risk_level.upper()}"
    ]]
    score_table = Table(score_data, colWidths=[8*cm, 8*cm])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#EEEDFE")),
        ("BACKGROUND", (1, 0), (1, 0), risk_color),
        ("TEXTCOLOR", (1, 0), (1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 14),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWHEIGHT", (0, 0), (-1, -1), 1.2*cm),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 0.5*cm))

    # Profile stats table
    story.append(Paragraph("Profile Overview", styles["h2"]))
    stats_data = [
        ["Metric", "Value"],
        ["Followers", f"{profile.get('follower_count', 0):,}"],
        ["Following", f"{profile.get('following_count', 0):,}"],
        ["Total Posts", f"{profile.get('post_count', 0):,}"],
        ["Verified", "Yes" if profile.get("is_verified") else "No"],
        ["Engagement Rate", f"{features.get('engagement_rate', 0):.2f}%"],
        ["Ghost Follower Est.", f"{features.get('ghost_follower_estimate', 0)*100:.0f}%"],
    ]
    stats_table = Table(stats_data, colWidths=[8*cm, 8*cm])
    stats_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#534AB7")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F8F8")]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ROWHEIGHT", (0, 0), (-1, -1), 0.8*cm),
    ]))
    story.append(stats_table)
    story.append(Spacer(1, 0.5*cm))

    # Signal flags
    story.append(Paragraph("Detected Signals", styles["h2"]))
    for signal in result.top_signals:
        flag_color = {"red": "#E24B4A", "orange": "#EF9F27", "green": "#1D9E75"}.get(signal["flag"], "#888")
        story.append(Paragraph(
            f'<font color="{flag_color}">●</font> <b>{signal["signal"]}</b>: {signal["value"]}',
            styles["Normal"]
        ))
    story.append(Spacer(1, 0.5*cm))

    # AI summary
    story.append(Paragraph("Sponsor Recommendation", styles["h2"]))
    story.append(Paragraph(ai_summary, styles["Normal"]))
    story.append(Spacer(1, 1*cm))
    story.append(Paragraph(
        "Generated by Instagram Fake Follower Detector · github.com/adheir01",
        ParagraphStyle("footer", fontSize=8, textColor=colors.gray)
    ))

    doc.build(story)
    return buffer.getvalue()
